# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: f7834cf405828c6e228caa82bc50e96cfde8d04889718abdfccb543d675c5f054a2c286b2911ea610d940484ddd7b81daae71bd044d875dcc7dd86aab59a7919

test:
  secret_key_base: 096ed613ff301106e5f8f53f629289d0c359be4d3225b120e82f26bc04befa8960a5f2972bade1baf2a552c53d5189bbb876f451989e9b92c7985444cef96216

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
